# Generated by Django 5.2.8 on 2026-01-08 20:57

import django.core.validators
import django.db.models.deletion
import face_study.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=face_study.models.image_upload_path)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_rated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_sessions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_per_session', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='face_study.faceimage')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='face_study.participant')),
            ],
            options={
                'unique_together': {('participant', 'image')},
            },
        ),
        migrations.CreateModel(
            name='EmotionRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_study.emotionalstate')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_rankings', to='face_study.imagerating')),
            ],
            options={
                'ordering': ['rating', 'rank'],
                'unique_together': {('rating', 'rank')},
            },
        ),
    ]
